# Generated by Django 4.1.3 on 2022-11-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreference',
            old_name='Unit',
            new_name='unit',
        ),
    ]
